apiVersion: v1
kind: Service
metadata:
  name: knowledge-docs-service
spec:
  type: NodePort
  selector:
    app: knowledge-docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Puedes acceder en http://localhost:30080 si usas Minikube
